name: Localization Reference Key Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-key-references:
    name: "Check Localization Keys are referenced"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: .github/workflows/localization/check-key-references.pip.txt
      - name: Install dependencies
        run: pip install .github/workflows/localization/check-key-references.pip.txt
      - name: Check Localization Key References
        run: python .github/workflows/localization/check-key-references.py
